M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Fri 14 Jul 2023 21:47:47 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-14T21:47:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X147.0Y-87.5
T2
X164.5Y-54.5
T0
M30
